### ISSUE TITLE
CDAWG suffix link

### ISSUE THREAD

**Issue by hdbn** [kg86/visds#28]
it seems that the suffix link of the sink node of CDAWG always points to itself, which is not correct.
https://kg86.github.io/visds/dist/vis_cdawg.html

**Comment by kg86** [comment]
Could you give an actual example?

**Comment by hdbn** [comment]
The default string on the above page is an example. Also, any string seems to be like that.
![スクリーンショット 2022-05-20 17 46 06](https://user-images.githubusercontent.com/8953940/169490836-8dd31103-c4a1-4367-b9e7-45978099594d.png)

**Comment by kg86** [comment]
Thanks, yes, it is incorrect. I'll take look at it.

**Comment by kg86** [comment]
Now, it's fixed.
<img width="606" alt="image" src="https://user-images.githubusercontent.com/5166128/169629204-872b7286-b652-4e06-8544-6e998e07bc5c.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/5166128/169629211-b513e76f-a47e-4524-bf3d-0e80fb2b7f46.png">

**Comment by hdbn** [comment]
Is it correct that there is no suffix link for the sink in the case of 'coc'?
<img width="838" alt="スクリーンショット 2022-05-21 11 12 56" src="https://user-images.githubusercontent.com/8953940/169630513-21d82245-bf1d-40e5-ab07-6a998ead811e.png">

**Comment by kg86** [comment]
This is a good point to discuss. I was wondering how should I handle this.
In this case, the suffix link of sink node should points to `c`, but it is an implicit node on the edge `coc`.
I think there are two ways for handle this by showing or not showing a suffix link to an implicit node.
I chose the latter case.
If showing it, we have to create an implicit node for this, and I would like to avoid such a specil handling.

Please let me know if you have a better solution about this.

**Comment by kg86** [comment]
Or shoud we always create `c` as an explicit node regardless to suffix links?

**Comment by hdbn** [comment]
I see. I think it is correct, as you are considering the implicit CDAWG in the [online construction](https://doi.org/10.1016/j.dam.2004.04.012) (cf Fig 5,11).
The [conference version](https://doi.org/10.1007/3-540-48194-X_16) just says suffix links are not defined for the sink, but having it when it can be defined is better I guess.

**Comment by kg86** [comment]
Thank you for the comment and useful pointers. Yes, it would be great to have an option switching the definition implicit or non-implicit versions. I added the option in https://github.com/kg86/visds/pull/31.

**Comment by kg86** [comment]
Close since the bug seems to be fixed.
